version: '3.8'

services:
  mongo-wasipay:
    container_name: mongo-wasipay
    image: mongo:latest
    hostname: host-mongo
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongo_wasipay/data:/data/db
      - /opt/mongo_wasipay/log:/var/log/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: wasipay
      MONGO_INITDB_ROOT_PASSWORD: wasipay